---
title: "Elections présidentielles de 2022 : quelle abstention peut-on prévoir ?  "
author: "Tom-Hadrian SY & Claire GIRAUD"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    orientation: columns
    vertical_layout: fill
    navbar:
      - { title: "Moodle", href: "https://tice.agrocampus-ouest.fr/course/view.php?id=6726", align: right }
params:
  setup_path: ../resources/
---

<style>                     
.navbar {
  background-color:#FFC300;
  border-color:#F5B041;
}
.navbar-brand {
color:black!important;
}

</style>  


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r lib, include=FALSE}
library(flexdashboard)
library(sf)
library(tidyverse)
library(tidyr)
library(ggplot2)
library(cowplot)
library(grid)
library(gridExtra)
library(openxlsx)
library(stringi)
```



```{r data dep, include=FALSE}
# importation du shapefile des départements
dpt_shape <-  st_read(dsn = 'In/contour-des-departements.geojson',
                      quiet=TRUE)
```

```{r data 2017, include=FALSE}
# importation du jeu de données pour 2017
ele_17 <- read.csv("In/Presidentielle_2017_Resultats_Département_T1_clean.csv", encoding = 'UTF-8')
ele_17 <- ele_17[-(97:106),-(28:49)] # On enlève les colonnes inutiles et les départements d'outre-mer. 

# Transformation pour déplacer deux lignes qui posent problème lors de la jointure
ele_17_t <- as.data.frame(t(as.matrix(ele_17)))
ele_17_t <- ele_17_t%>%
  relocate(20,.after = 6)
ele_17_t <- ele_17_t%>%
  relocate(21,.before = 7)
ele_17 <- as.data.frame(t(as.matrix(ele_17_t)))
ele_17$Abstentions_ins <- as.numeric(ele_17$Abstentions_ins)

# Récupération des codes des départements pour le jeu de données de 2012.
code_dep <- c(ele_17[,1])
```

```{r data 2012, include=FALSE}
# importation du jeu de données pour 2017
ele_12 <- read.csv("In/France-politique-2012.csv", encoding='UTF-8', sep=";")
ele_12 <- ele_12[-(97:107),]# On enlève les départements d'outre-mer. 

# Transformation pour déplacer deux lignes qui posent problème lors de la jointure
ele_12_t <- as.data.frame(t(as.matrix(ele_12)))
ele_12_t <- ele_12_t%>%
  relocate(20,.after = 6)
ele_12_t <- ele_12_t%>%
  relocate(21,.before = 7)
ele_12 <- as.data.frame(t(as.matrix(ele_12_t)))
ele_12$Participation <- as.numeric(ele_12$Participation)

# transformation pour obtenir l'abstention et les codes des départements
# Correction du problème pour la jointure pour deux départements
ele_12 <- ele_12 %>%
  mutate(code = code_dep)%>%
  mutate(Abstention = 100-Participation) %>%
  mutate(Département = replace(Département, Département == 'CORSE SUD', 'CORSE DU SUD')) %>% 
  mutate(Département = replace(Département, Département == 'SEINE SAINT-DENIS', 'SEINE SAINT DENIS'))
```

```{r new data, include=FALSE}
# Calcul de la différence entre 2012 et 2017 pour l'abstention
diff_abst <- ele_17$Abstentions_ins-ele_12$Abstention

#Création d'un nouveau jeu de données
new_dta <- data.frame(code=code_dep, diff_abs = diff_abst)

# Création de variables catégorielles
new_dta <- new_dta %>%
  mutate(Abst_cat = case_when(diff_abst < 0 ~ "diminution", 
                        diff_abst > 2.5 ~ "augmentation",
                        TRUE ~ "maintien ou faible augmentation"))
```

```{r data pauv 2017, include = FALSE}
pauv_17 <- read.xlsx('In/pauvrete.xlsx')
pauv_17 <- pauv_17[-(97:101),]
```

```{r data pauv 2012, include = FALSE}
pauv_12 <- read.xlsx('In/base-cc-filosofi-12.xlsx', sheet=4, startRow = 6)

pauv_12 <- pauv_12 %>% 
  select(2,TP6012) %>% 
  rename(Département=LIBGEO) %>% 
  rename(Pauvrete=TP6012) %>% 
  mutate(Dep_formatted = str_to_upper(
    stri_trans_general(
      gsub('-',' ',Département), "Latin-ASCII"))) %>% 
  select(-Département)
```

```{r data pauv 2022 (2018), include = FALSE}
pauv_18 <- read.csv('In/data_pauv_2018.csv', sep=';', encoding='UTF-8', skip=2)

# On renomme la colonne contenant les départements et celle avec la pauvreté et on uniformise l'écriture.
pauv_18 <- pauv_18 %>% 
  mutate(Dep = str_to_upper(
  stri_trans_general(
    gsub('-',' ',Libellé), "Latin-ASCII"))) %>% 
  rename(Pauvrete=Taux.de.pauvreté.2018) %>% 
  slice(-c(97:101))%>% 
  mutate(Annee=rep(2021,length(Dep))) %>% 
  select(Annee, Dep, Pauvrete)
```



```{r join, include=FALSE}
# Jointure entre le nouveau jeu de données et le shapefile
dta_dif <- dpt_shape %>% 
  inner_join(y = new_dta, by = "code")

# Jointure par départements avec les fichiers contenant le taux de pauvreté 
dta_pauv_17<- inner_join(pauv_17,
                         ele_17,
                         by=c('Département'='Département')) 

dta_pauv_12 <- inner_join(ele_12, 
                          pauv_12, 
                          by=c('Département'='Dep_formatted'))

# Pour l'affichage des labels sur le graphique n°2
dta_pauv_12 <- dta_pauv_12 %>% 
  mutate(Département = replace(Département, 
                       Département == 'HAUTE CORSE', 
                       'Haute-Corse'))%>%
  mutate(Département = replace(Département, 
                       Département == 'CORSE DU SUD', 
                       'Corse-du-Sud'))%>%
  mutate(Département = replace(Département, 
                       Département == 'SEINE SAINT DENIS', 
                       'Seine-Saint_Denis'))
```

```{r join 2, include = FALSE}
# modification du fichier issu de la jointure 2017
dta_pauv_17_bis <- dta_pauv_17 %>% 
  mutate(Dep = str_to_upper(
    stri_trans_general(
      gsub('-',' ',Département), "Latin-ASCII"))) %>% 
  select(-Département) %>% 
  rename(Abstention=Abstentions_ins) %>% 
  rename(Pauvrete=Taux.de.pauvreté) %>% 
  mutate(Annee=rep(2017,length(Dep))) %>% 
  select(Annee,Dep,Abstention,Pauvrete)

# Modification fichier issu de la jointure 2012
dta_pauv_12_bis <- dta_pauv_12 %>%
  rename(Dep=Département) %>%
  mutate(Annee=rep(2012,length(Dep))) %>% 
  select(Annee,Dep,Abstention,Pauvrete)

# Fusion des deux jointures modifiées
dta_12_17 <- rbind(dta_pauv_12_bis, dta_pauv_17_bis)
```



```{r mod, include=FALSE}
dta_12_17$Annee <- as.numeric(dta_12_17$Annee)

# Modèle d'Analyse de la Covariance
mod <- lm(Abstention~Pauvrete*Annee, data=dta_12_17)
anova(mod)

pauv_18$abs_pred <- predict(mod, newdata=pauv_18)

# µ <- mod$coefficients[1]
# beta <- mod$coefficients[2]
# alpha2 <- mod$coefficients[3]
# gamma3 <- mod$coefficients[3]*2
```



```{r crea carte plot 1, include=FALSE}
# Création du premier graphique
cartedif <- dta_dif %>% 
  ggplot2::ggplot() +
  geom_sf(aes(fill= Abst_cat)) + #coloration des départements en fonction d'abstention
  scale_fill_manual(values=list("augmentation" = "indianred2", 
                                "maintien ou faible augmentation" = "gray88", 
                                "diminution" = "seagreen2" ))+ # changement des couleurs de remplissage
  labs(fill = "Évolution abstention")+ # changement du titre de la légende
  theme_classic() + # thème sans grille
  ggtitle("Evolution de l'abstention aux élections \nprésidentielles entre 2012 et 2017")+ # ajout du titre
  theme(plot.title=element_text( hjust=0.5, 
                                 vjust=0.5, 
                                 face='bold'))+ # Mise en forme du titre
  annotate("rect", 
           xmin=c(8.2), xmax=c(9.8),
           ymin=c(41.2) , ymax=c(43.2),
           alpha=0.2, 
           color="black", 
           fill="grey", 
           size=1)+ # ajout d'un rectangles pour mettre en valeur certains départements
    annotate("text", 
            label = "Seine-Saint-Denis", 
            x = 7, y = 51.1 , 
            vjust = 0, fontface ="italic", size = 3) +
  annotate("segment", 
            x = 7, 
            xend = 2.6, 
            y = 51, 
            yend = 49, 
            colour = "black", 
            size=0.5, 
            arrow=arrow(length=unit(1.8, "mm")))+
  theme(axis.line=element_blank(),
        axis.text.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks=element_blank(), 
        axis.title.x = element_text(color="white", size=0), 
        axis.title.y = element_text(color="white", size=0))
  # Suppression des axes et de leurs labels
```

```{r crea regression plot 2, include = FALSE}
plot2 <- ggplot() +
  
  geom_point(data=dta_pauv_12, 
             aes(x=Pauvrete, 
                 y=Abstention, 
                 col='2012')) +
  
  
  geom_smooth(data=dta_pauv_12, 
              aes(x=Pauvrete, 
                  y=Abstention, 
                  col='2012'),
              method='lm', 
              se=F) +
  
  geom_text(data=dta_pauv_12 %>% 
              filter(Abstention>25), 
            nudge_x=-2.6, 
            size=3.5,
            aes(x=Pauvrete, 
                y=Abstention, 
                label=Département, 
                col='2012')) +
  
  geom_point(data=dta_pauv_17, 
             aes(x=Taux.de.pauvreté, 
                 y=Abstentions_ins, 
                 col='2017')) +
  
  geom_smooth(data=dta_pauv_17, 
              aes(x=Taux.de.pauvreté, 
                  y=Abstentions_ins, 
                  col='2017'), 
              method='lm', 
              se=F) +
  
  geom_text(data=dta_pauv_17 %>% 
              filter(Abstentions_ins>25, 
                               Taux.de.pauvreté<25), 
            nudge_x=-2.5, 
            size=3.5,
            aes(x=Taux.de.pauvreté, 
                y=Abstentions_ins, 
                label=Département, 
                col='2017')) + 
  
  geom_text(data=dta_pauv_17 %>% 
              filter(Abstentions_ins>25, 
                     Taux.de.pauvreté>25), 
            nudge_x=-3,
            size=3.5,
            aes(x=Taux.de.pauvreté, 
                y=Abstentions_ins, 
                label=Département, 
                col='2017')) + 
  
  
  scale_color_manual(values=list('2012'='skyblue3',
                                 '2017'='sienna1')) +
  labs(x='Taux de pauvreté',
       y="Taux d\'abstention aux élections",
       col='Année') + 
  theme_light() +
  ggtitle("Comparaison des relations taux de pauvreté - taux \nd\'abstention en 2012 et en 2017")+ # ajout du titre
  theme(plot.title=element_text( hjust=0.5, 
                                 vjust=0.5, 
                                 face='bold')) # Mise en forme du titre
  
  
```

```{r crea prediction plot 3, include=FALSE}
plot3 <- ggplot() +
  
  geom_smooth(data=dta_pauv_12, 
              aes(x=Pauvrete, 
                  y=Abstention, 
                  col='2012'),
              method='lm', 
              se=F) +
  
  geom_smooth(data=dta_pauv_17, 
              aes(x=Taux.de.pauvreté, 
                  y=Abstentions_ins, 
                  col='2017'), 
              method='lm', 
              se=F) +
  
  geom_smooth(data=pauv_18, 
              aes(x=Pauvrete, 
                  y=abs_pred, 
                  col='2022'),
              method='lm', 
              se=F, size=2) +
  
  scale_color_manual(values=list('2012'='skyblue3',
                                 '2017'='sienna1',
                                 '2022'='red')) +
  
  labs(x='Taux de pauvreté',
       y="Taux d\'abstention aux élections",
       col='Année') +
  
  theme_light() + 
  
  ggtitle("Projection de la relation taux de pauvreté - taux \nd'abstention en 2022")+ # ajout du titre
  theme(plot.title=element_text( hjust=0.5, 
                                 vjust=0.5, 
                                 face='bold')) # Mise en forme du titre
  
```


Preview {data-icon="fa-signal"}
===================================== 

Column 1
--------------------------------------------------

### Etape 1
```{r preview graph 1}
# affichage de la première carte
plot(cartedif)
```

Column 2
--------------------------------------------------

### Etape 2

```{r preview graph 2}
plot(plot2)
```

### Etape 3

```{r preview graph 3}
plot(plot3)
```

Observation initiale {data-icon="fa-signal"}
=====================================     

### Observation initiale
    
```{r graph 1}
# Affichage de la carte dans une page unique
plot(cartedif)
```

Regression {data-icon="fa-signal"}
=====================================      
### Régression

```{r graph 2}
plot(plot2)
```

Prédiction {data-icon="fa-signal"}
=====================================     

### Prédiction

```{r graph 3}
plot(plot3)
```




